### ISSUE TITLE
Lack possibility to generate at same seed range

### ISSUE THREAD

**Issue by andersonfaaria** [eps696/stylegan2#1]
The inference method in this repository seems very restricted in comparison to regular stylegan2.
We basically only have latent walk and everytime it is run it return you random outputs.

Can you please try to include at least a seed range controller for latent_anima? I noticed there are some similarities in 

get_z of utilgan.py with generate_zs_from_seeds of run_generator.py (default stylegan2) but I was not able to apply the same logic.

**Comment by eps696** [comment]
this combo (random walk + latent select/replay + projection) covered pretty much all my needs, so i might miss something. 
could you pls explain, what do you mean by seed range? the seed value is fixed [here](https://github.com/eps696/stylegan2/blob/f2ae70aa92657a684e750ea94c46aaba7a849cea/src/_genSGAN2.py#L38); do you want to have exposed to command line arguments? 
(i don't see much sense in generating single images for specific seeds, cause there's no any logical correspondence between such seeds and results anyway)

**Comment by andersonfaaria** [comment]
In regular stylegan2 repo we had several options such as:
- Inference: Generate one output given a seed or interval of seeds and truncation.
- Truncation: Generate several snapshopts of a single seed varying the truncation.
- Interpolation: Basically the latent walk, but you could define if the walk-type was in W or Z and you could give a list of seeds to use.
- Noise Loop or just Random Walk: Similar to interpolation, but you just pass seed (doesn't change anything), starting seed (obligatory the seed where you start random walking from) and the distance in latent space where you can reach.

From those, noise loop is the least useful of them all. Unless you save the images as their seed number, this way we could pick this value and use later inference to vary those versions to achieve the best output we want.

There's also two another options:
- Mixing Seeds (Style Mixing): Multiply the latent vectors one by another to get the resulting model.
- Near Neighbors: This one is basically a latent walk in W searching for models near the given seed, you could pass number of samples, distant they could go, truncation and seed. It's pretty useful when you want to try and find better versions of a desired output.

Your repo so far is one of the best I've encountered, but only having random walk (projection didn't worked for me) is a buzzkiller

**Comment by eps696** [comment]
well, the options in the original repo were showcasing the principal possibilities, while my goal was to make a useful video tool of those possibilities. if you insist that they are really crucial for some pipelines, i may add them back (not a top priority though).

still i do not get why you may need the seed as a controlling input. i use saved dlatents (w-vectors) here as control points, which behave the same for both random/generated images and projected ones, while storing real vectors instead of some random magic number. they also let you address images at the interpolated in-between latents points, which you'll never get with those quantized seed values. 

near neighbours sounds reasonable, i may add it one day. 
mixing styles is in fact quite a huge topic on its own; i thought of exposing some controls for it, but on my practice i nearly never faced the same task twice, so didn't want to overload the code by a heap of rarely used functions. after all, when a user comes that far, they probably should be able to tweak some python themselve. (btw, latents vectors are summed, not multiplied)

**Comment by eps696** [comment]
here is recent fix:
`--seed X` is added as a command line option and the form entry to colab.
set it to some positive integer to get fixed repeatable results (0 = random).
since this was a main topic of this issue, i close it for now. 
please reopen, if it doesn't work for some reason, or start new one(s) if there are derivative ideas about that.
